module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/ENTER_URL👈?mode=ac_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/5cs2pd.jpg',
    NEWSLETTER_JID: '120363404570861723@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝚔𝚞𝚛𝚊𝚖𝚊 𝚖𝚒𝚗𝚒 ʙᴏᴛ ',
    OWNER_NAME: '𝚌𝚑𝚊𝚌𝚔𝚛𝚊',
    OWNER_NUMBER: '9477 5245719',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ 𝚌𝚑𝚊𝚌𝚔𝚛𝚊',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBuUt0GehELthXzZI0w',
};
